name: chezmoi
on:
  push:
    paths:
      - .github/workflows/chezmoi.yml
      - "dockerfiles/chezmoi/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/chezmoi.yml
      - "dockerfiles/chezmoi/**"
      - .github/workflows/reusable.yml

jobs:
  chezmoi:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: chezmoi
      version: v2.42.3
