name: Docker Hub description
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  docker-hub-description:
    if: github.repository == 'kbuley/gluetun'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: kbuley
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: kbuley/binpot
          short-description: The statically compiled, cross architecture, Docker based, binaries pot.
          readme-filepath: README.md
