name: gocov
on:
  push:
    paths:
      - .github/workflows/gocov.yml
      - "dockerfiles/gocov/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/gocov.yml
      - "dockerfiles/gocov/**"
      - .github/workflows/reusable.yml

jobs:
  golangci-lint:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: gocov
      version: v1.1.0
