name: lazygit
on:
  push:
    paths:
      - .github/workflows/lazygit.yml
      - "dockerfiles/lazygit/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/lazygit.yml
      - "dockerfiles/lazygit/**"
      - .github/workflows/reusable.yml

jobs:
  lazygit:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: lazygit
      version: v0.40.2
