on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x,linux/riscv64

jobs:
  verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3

      - run: docker build dockerfiles/${{inputs.name}}

  publish:
    if: |
      github.repository == 'kbuley/binpot' &&
      github.event_name == 'push' &&
      github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v2
        with:
          username: kbuley
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=created::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo ::set-output name=revision::$(git rev-parse --short HEAD)

      - name: Build and push final image
        uses: docker/build-push-action@v3
        with:
          context: dockerfiles/${{ inputs.name }}
          platforms: ${{inputs.platforms}}
          build-args: |
            VERSION=${{ inputs.version }}
            CREATED=${{ steps.vars.outputs.created }}
            REVISION=${{ steps.vars.outputs.revision }}
          tags: |
            kbuley/binpot:${{ inputs.name }}
            kbuley/binpot:${{ inputs.name }}-${{ inputs.version }}
          push: true
