on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/arm64

jobs:
  verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v4.1.1

      - run: docker build dockerfiles/${{inputs.name}}

  publish:
    if: |
      github.repository == 'kbuley/binpot' &&
      github.event_name == 'push' &&
      github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: kbuley
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: kbuley+github
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/${{ inputs.name }}
          platforms: ${{inputs.platforms}}
          build-args: |
            VERSION=${{ inputs.version }}
            CREATED=${{ steps.vars.outputs.created }}
            REVISION=${{ steps.vars.outputs.revision }}
          tags: |
            kbuley/binpot:${{ inputs.name }}
            kbuley/binpot:${{ inputs.name }}-${{ inputs.version }}
            quay.io/kbuley/binpot:${{ inputs.name }}
            quay.io/kbuley/binpot:${{ inputs.name }}-${{ inputs.version }}
          push: true
